channels:
- anaconda
- conda-forge
dependencies:
- python=3.9.*
- lightgbm=3.3.2
- pandas=1.5.0
- scikit-learn=1.1.2
- typer=0.6.1
- pyarrow=9.0.0
- matplotlib=3.6.0
- pip
- pip:
  - azureml-mlflow==1.45.0
  - azureml-core==1.45.0
